# Generated by Django 4.2.7 on 2023-11-19 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='char_id',
            field=models.CharField(default=234568, max_length=50, verbose_name='Ссылка на Телеграмм'),
            preserve_default=False,
        ),
    ]
