# Generated by Django 4.2.7 on 2023-11-21 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_char_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='char_id',
            new_name='chat_id',
        ),
    ]
