# Generated by Django 4.2.7 on 2023-11-24 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_char_id_user_chat_id'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
