# Generated by Django 4.2.7 on 2023-11-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_alter_habit_is_published_alter_habit_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='periodicity',
            field=models.CharField(blank=True, choices=[('1', 'раз в день'), ('2', 'раз в 2 дня'), ('3', 'раз в 3 дня'), ('4', 'раз в 4 дня'), ('5', 'раз в 5 дней'), ('6', 'раз в 6 дней'), ('7', 'раз в 7 дней')], default=1, max_length=10, null=True, verbose_name='Периодичность'),
        ),
    ]
